let tags = [
[ "Chord", "Note1", "Note2", "Note3", "Note4", "r1", "WebNote1", "WebNote2", "WebNote3", "WebNote4", "r2", "Info"] ,
[ "C major", "C", "E", "G", "n", "|", "C", "E", "G", "n", "|", "n"] ,
[ "C# major", "Cs", "F", "Gs", "n", "|", "C#", "E#", "G#", "n", "|", "n"] ,
[ "D major", "D", "Fs", "A", "n", "|", "D", "F#", "A", "n", "|", "n"] ,
[ "Eb major", "Gs", "G", "As", "n", "|", "Eb", "G", "Bb", "n", "|", "n"] ,
[ "E major", "E", "Gs", "B", "n", "|", "E", "G#", "B", "n", "|", "n"] ,
[ "F major", "F", "A", "C", "n", "|", "F", "A", "C", "n", "|", "n"] ,
[ "F# major", "Fs", "As", "Cs", "n", "|", "F#", "A#", "C#", "n", "|", "n"] ,
[ "G major", "G", "B", "D", "n", "|", "G", "B", "D", "n", "|", "n"] ,
[ "Ab major", "Gs", "C", "Ds", "n", "|", "Ab", "C", "Eb", "n", "|", "n"] ,
[ "A major", "A", "Cs", "E", "n", "|", "A", "C#", "E", "n", "|", "n"] ,
[ "Bb major", "As", "D", "F", "n", "|", "Bb", "D", "F", "n", "|", "n"] ,
[ "B major", "B", "Ds", "Fs", "n", "|", "B", "D#", "F#", "n", "|", "n"] ,
[ "C minor", "C", "Ds", "G", "n", "|", "C", "Eb", "G", "n", "|", "n"] ,
[ "C# minor", "Cs", "E", "Gs", "n", "|", "C#", "E", "G#", "n", "|", "n"] ,
[ "D minor", "D", "F", "A", "n", "|", "D", "F", "A", "n", "|", "n"] ,
[ "Eb minor", "Gs", "Fs", "As", "n", "|", "Eb", "Gb", "Bb", "n", "|", "n"] ,
[ "E minor", "E", "G", "B", "n", "|", "E", "G", "B", "n", "|", "n"] ,
[ "F minor", "F", "Gs", "C", "n", "|", "F", "Ab", "C", "n", "|", "n"] ,
[ "F# minor", "Fs", "A", "Cs", "n", "|", "F#", "A", "C#", "n", "|", "n"] ,
[ "G minor", "G", "As", "D", "n", "|", "G", "Bb", "D", "n", "|", "n"] ,
[ "Ab minor", "Gs", "B", "Ds", "n", "|", "Ab", "Cb(B)", "Eb", "n", "|", "n"] ,
[ "A minor", "A", "C", "E", "n", "|", "A", "C", "E", "n", "|", "n"] ,
[ "Bb minor", "As", "Cs", "F", "n", "|", "Bb", "Db", "F", "n", "|", "n"] ,
[ "B minor", "B", "D", "Fs", "n", "|", "B", "D", "F#", "n", "|", "n"] ,
[ "C diminished", "C", "Ds", "Fs", "n", "|", "C", "Eb", "Gb", "n", "|", "n"] ,
[ "C# diminished", "Cs", "E", "G", "n", "|", "C#", "E", "G", "n", "|", "n"] ,
[ "D diminished", "D", "F", "Gs", "n", "|", "D", "F", "Ab", "n", "|", "n"] ,
[ "Eb diminished", "Gs", "Fs", "A", "n", "|", "Eb", "Gb", "Bbb(A)", "n", "|", "Bbb is 5th above root (E not flat) and is A note."] ,
[ "E diminished", "E", "G", "As", "n", "|", "E", "G", "Bb", "n", "|", "n"] ,
[ "F diminished", "F", "Gs", "B", "n", "|", "F", "Ab", "Cb(B)", "n", "|", "n"] ,
[ "F# diminished", "Fs", "A", "C", "n", "|", "F#", "A", "C", "n", "|", "n"] ,
[ "G diminished", "G", "As", "Cs", "n", "|", "G", "Bb", "Db", "n", "|", "n"] ,
[ "Ab diminished", "Gs", "Ds", "D", "n", "|", "Ab", "Cb", "Ebb(D)", "n", "|", "n"] ,
[ "A diminished", "A", "C", "Ds", "n", "|", "A", "C", "Eb", "n", "|", "n"] ,
[ "Bb diminished", "As", "Cs", "E", "n", "|", "Bb", "Db", "Fb(E)", "n", "|", "n"] ,
[ "B diminished", "B", "D", "F", "n", "|", "B", "D", "F", "n", "|", "n"] ,
[ "C major seventh", "C", "E", "G", "B", "|", "C", "E", "G", "B", "|", "n"] ,
[ "C# major seventh", "Cs", "F", "Gs", "C", "|", "C#", "E#(F)", "G#", "B#(C)", "|", "n"] ,
[ "D major seventh", "D", "Fs", "A", "Cs", "|", "D", "F#", "A", "C#", "|", "n"] ,
[ "Eb major seventh", "Gs", "G", "As", "D", "|", "Eb", "G", "Bb", "D", "|", "n"] ,
[ "E major seventh", "E", "Gs", "B", "Ds", "|", "E", "G#", "B", "D#", "|", "n"] ,
[ "F major seventh", "F", "A", "C", "E", "|", "F", "A", "C", "E", "|", "n"] ,
[ "F# major seventh", "Fs", "As", "Cs", "F", "|", "F#", "A#", "C#", "E#(F)", "|", "n"] ,
[ "G major seventh", "G", "B", "D", "Fs", "|", "G", "B", "D", "F#", "|", "n"] ,
[ "Ab major seventh", "Gs", "C", "Ds", "G", "|", "Ab", "C", "Eb", "G", "|", "n"] ,
[ "A major seventh", "A", "Cs", "E", "Gs", "|", "A", "C#", "E", "G#", "|", "n"] ,
[ "Bb major seventh", "As", "D", "F", "A", "|", "Bb", "D", "F", "A", "|", "n"] ,
[ "B major seventh", "B", "Ds", "Fs", "As", "|", "B", "D#", "F#", "A#", "|", "n"] ,
[ "C dominant seventh", "C", "E", "G", "As", "|", "C", "E", "G", "Bb", "|", "n"] ,
[ "C# dominant seventh", "Cs", "F", "Gs", "B", "|", "C#", "E#(F)", "G#", "B", "|", "n"] ,
[ "D dominant seventh", "D", "Fs", "A", "C", "|", "D", "F#", "A", "C", "|", "n"] ,
[ "Eb dominant seventh", "Gs", "G", "As", "Cs", "|", "Eb", "G", "Bb", "Db", "|", "n"] ,
[ "E dominant seventh", "E", "Gs", "B", "D", "|", "E", "G#", "B", "D", "|", "n"] ,
[ "F dominant seventh", "F", "A", "C", "Ds", "|", "F", "A", "C", "Eb", "|", "n"] ,
[ "F# dominant seventh", "Fs", "As", "Cs", "E", "|", "F#", "A#", "C#", "E", "|", "n"] ,
[ "G dominant seventh", "G", "B", "D", "F", "|", "G", "B", "D", "F", "|", "n"] ,
[ "Ab dominant seventh", "Gs", "C", "Ds", "Fs", "|", "Ab", "C", "Eb", "Gb", "|", "n"] ,
[ "A dominant seventh", "A", "Cs", "E", "G", "|", "A", "C#", "E", "G", "|", "n"] ,
[ "Bb dominant seventh", "As", "D", "F", "Gs", "|", "Bb", "D", "F", "Ab", "|", "n"] ,
[ "B dominant seventh", "B", "Ds", "Fs", "A", "|", "B", "D#", "F#", "A", "|", "n"] ,
[ "C minor seventh", "C", "Ds", "G", "As", "|", "C", "Eb", "G", "Bb", "|", "n"] ,
[ "C# minor seventh", "Cs", "E", "Gs", "B", "|", "C#", "E", "G#", "B", "|", "n"] ,
[ "D minor seventh", "D", "F", "A", "C", "|", "D", "F", "A", "C", "|", "n"] ,
[ "Eb minor seventh", "Gs", "Fs", "As", "Cs", "|", "Eb", "Gb", "Bb", "Db", "|", "n"] ,
[ "E minor seventh", "E", "G", "B", "D", "|", "E", "G", "B", "D", "|", "n"] ,
[ "F minor seventh", "F", "Gs", "C", "Ds", "|", "F", "Ab", "C", "Eb", "|", "n"] ,
[ "F# minor seventh", "Fs", "A", "Cs", "E", "|", "F#", "A", "C#", "E", "|", "n"] ,
[ "G minor seventh", "G", "As", "D", "F", "|", "G", "Bb", "D", "F", "|", "n"] ,
[ "Ab minor seventh", "Gs", "B", "Ds", "Fs", "|", "Ab", "Cb(B)", "Eb", "Gb", "|", "n"] ,
[ "A minor seventh", "A", "C", "E", "G", "|", "A", "C", "E", "G", "|", "n"] ,
[ "Bb minor seventh", "As", "Cs", "F", "Gs", "|", "Bb", "Db", "F", "Ab", "|", "n"] ,
[ "B minor seventh", "B", "D", "Fs", "A", "|", "B", "D", "F#", "A", "|", "n"] ,
[ "C minor seventh flat five", "C", "Ds", "Fs", "As", "|", "C", "Eb", "Gb", "Bb", "|", "n"] ,
[ "C# minor seventh flat five", "Cs", "E", "G", "B", "|", "C#", "E", "G", "B", "|", "n"] ,
[ "D minor seventh flat five", "D", "F", "Gs", "C", "|", "D", "F", "Ab", "C", "|", "n"] ,
[ "Eb minor seventh flat five", "Gs", "Fs", "A", "Cs", "|", "Eb", "Gb", "Bbb(A)", "Db", "|", "n"] ,
[ "E minor seventh flat five", "E", "G", "As", "D", "|", "E", "G", "Bb", "D", "|", "n"] ,
[ "F minor seventh flat five", "F", "Gs", "B", "Ds", "|", "F", "Ab", "Cb(B)", "Eb", "|", "n"] ,
[ "F# minor seventh flat five", "Fs", "A", "C", "E", "|", "F#", "A", "C", "E", "|", "n"] ,
[ "G minor seventh flat five", "G", "As", "Cs", "F", "|", "G", "Bb", "Db", "F", "|", "n"] ,
[ "Ab minor seventh flat five", "Gs", "Ds", "D", "Fs", "|", "Ab", "Cb", "Ebb(D)", "Gb", "|", "n"] ,
[ "A minor seventh flat five", "A", "C", "Ds", "G", "|", "A", "C", "Eb", "G", "|", "n"] ,
[ "Bb minor seventh flat five", "As", "Cs", "E", "Gs", "|", "Bb", "Db", "Fb(E)", "Ab", "|", "n"] ,
[ "B minor seventh flat five", "B", "D", "F", "A", "|", "B", "D", "F", "A", "|", "n"] ,
[ "Chord", "Note1", "Note2", "Note3", "Note4", "r1", "WebNote1", "WebNote2", "WebNote3", "WebNote4", "r2", "Info"] 
];
